### ISSUE TITLE
5000 jobs limit on Colossus

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#14]
Currently there is a limit of 5000 jobs per users on Colossus. This is already higher than it was, e.g. on Abel (where the limit was 400). Nevertheless 5000 jobs is limiting, as typical scenario for imaging processing is to run one job per participant.

**Comment by ofrei** [comment]
Using GNU parallel to group multiple jobs, and run them concurrently within a node, could be a handy workaround. But it's important to tell parallel to display output as it arrives (something lie ``-k --lb`` )  otherwise debugging could be very dificult.
https://unix.stackexchange.com/questions/277981/gnu-parallel-immediately-display-job-stderr-stdout-one-at-a-time-by-jobs-order

**Comment by tobias-kaufmann** [comment]
_Just a brief example where the 5k is a limitation_: the main limitation here is not the fact that we cannot run >5000 jobs in parallel but rather that we cannot submit >5000 jobs at once. For example, say we want to process data from 30k subjects where each job processes 1 subjects. 
Limitation 1: we have to process data in batches, i.e. we submit the first 5k, then we wait, then we submit the next 5k, and so on. More effort / more administration
Limitation 2: An easy (sge-like) implementation would be to submit 30k jobs and then in each job pick a subject from the list of 30k subjects based on SLURM_ARRAY_TASK_ID. Since we are limited to submitting 5k jobs and thus SLURM_ARRAY_TASK_ID cannot be >5k, we have to implement a work-around for selecting which subject to process in which job (no big deal, but more effort).

**Comment by ofrei** [comment]
There is some confusion about this limit - the documentation says it's per project, but so far user experience in p33 says it's per user, i.e. if one user submits his 4500 jobs, then other users will still be able to submit more jobs.

https://www.uio.no/english/services/it/research/sensitive-data/use-tsd/hpc/queue-system.html
>Max 4500 submitted jobs (running or pending) per project (--account) at the same time.
>Max size of job arrays: 4000. That also means that the largest job array index is 4000. Note that an job array of size N will count as N jobs wrt. the total number of submitted jobs per project.
