### ISSUE TITLE
Let p33 reboot their own machine

### ISSUE THREAD

**Issue by danielroelfs** [norment/tsd_issues#19]
This might be resolved with #10, but a few times too often the RHEL7 is frozen for all p33 users, which is solved with a reboot of the system. It would be nice if a select few within p33 would get the rights to reboot the system, so we don't have to wait for second-line support at TSD to pick this up.

**Comment by ofrei** [comment]
@danielroelfs Discussed at TSD big users meeting. There is a clean need for this, and it may be implemented later. It somewhat depends on upgrading Linux VMs to Horizon VMWare, because Horizon VMWare has some of this functionality built in. It also somewhat depends on merging /cluster and /durable, because this will make mount points more stable. Otherwise  rebooting login nodes may not only resolve issues, but also introduce issues - e.g. VM may not even start / hang during startup (that's how I understood it). But this is on  TSD's list, in a long term.

**Comment by denvdm** [comment]
Perhaps drawing this issue a bit wider, was it also discussed why this freezing happens so often? Is it also more for p33 than for other projects? And, less seriously, but still annoying I (and I know others as well) routinely get ´the clock´ screen popping up in the middle of typing. Often easy to log in again, but still a nuisance.

**Comment by ofrei** [comment]
It was mentioned that the whole setup with RHEL7 login VM is sort of experimental - other projects get RHEL6 by default. My understanding is that in p33 the upgrade to RHEL7 was done because colossus runs RHEL7, so in order to use the modules environment on the login node it needs to be RHEL7. I'm not sure if or how many other TSD projects have the same, but it's not the default setting.

This is linked to #10 .

**Comment by ofrei** [comment]
Now we can ask @Sandeek to reboot our VMs .
