### ISSUE TITLE
Relocate memory of p33-tl02-l VM  to a new p33-submit VM

### ISSUE THREAD

**Issue by ofrei** [norment/tsd_issues#25]
Currently we have a large-memory VM called ``p33-tl02-l``, running Red Hat 6. It  does not have /cluster mounted, as a result we can't use modules on that VM, which render it nearly useless.
```
p33-tl01-l        (Red Hat 6)    -  8 GB ram
p33-tl02-l        (Red Hat 6)    - 128 GB ram
```
I suggest to reduce RAM on p33-tl02-l down to 8 GB (to make it consistent with p33-tl01-l). 
Instead we should request a second p33-submit node, having 128 GB of memory.

Do we agree on this?

**Comment by ofrei** [comment]
@scimerc Hi Francesco, currently I think it's only you using p33-tl02-l, is it OK to do what's described above?

**Comment by scimerc** [comment]
sure, no problem. 
I am just unsure about the p33-submit name. it sort of suggests that it will be *the* machine to submit jobs from, but this will be possible from other (rhel7) machines too, won't it? I would therefore recommend a name that is more in line with the existing ones.

**Comment by ofrei** [comment]
I think we could let TSD decide on names. But by default it's only pNN-submit nodes that have cluster access (as it is the case in p697) - p33 is an exception (more info #17).

**Comment by ofrei** [comment]
Ticket submitted - [rt.uio.no #3766053] Automatisk svar (AutoReply): Relocate memory of p33-tl02-l VM to a new VM that is similar to p33-submit.

@f-krull could you please take a look, is it a reasonable request?

**Comment by Sabryr** [comment]
Linux p33-tl01-l.xx / el6.x86_64  / 8Gb
Linux p33-tl02-l.xx / el6.x86_64 /128G
Linux p33-submit.xx  /el7.x86_64 /8G

IMO: One RedHat 6X VM is enough, for login in and for file transfer etc. Due to TSD infrastructure limitations this can not be RedHat7. But this require that all p33 user use the tl01 as a "login node" not for running processing pipe lines etc..
Then you can have 2 RedHat7 VMs, which you login through the tl01 and do your analysis. This way I can provide all software centrally (VM + cluster). i.e. you can use the same software to perform analysis on your private VM as well as on Cluster.

**Comment by ofrei** [comment]
@Sabryr Thanks! In p33 the login node is ``p33-rhel7-login.tsd.usit.no`` (for most p33 users). It runs RHEL7, and has 64 GB of ram. This memory is used well by people doing  interactive work on small data.  This solution is working well, we are afraid to touch it :) 

But ``p33-tl02-l.xx`` is running RHEL6. Which, in my view, a waste of 128 GB RAM (because /cluster is not mounted and we can't run modules there).

**Comment by ofrei** [comment]
This had been fixed some time ago. The up to date list of VMs is available in the wiki ( https://norment.awiki.org/dokuwiki/tsd-faq )
