### ISSUE TITLE
Problems installing LD SCore

### ISSUE THREAD

**Issue by E-Claire** [norment/tsd_issues#32]
After loading Anaconda and Python 2.7 I get the below error message. (The screenshot is from p471 but I get the same message on p697).
![ldsc_issue](https://user-images.githubusercontent.com/61872316/76081480-79745400-5fa9-11ea-8c35-a910f163a1f9.png)

**Comment by ofrei** [comment]
@E-Claire Hi there. For sure we need to find an easy way of running ldsc on TSD. 
I've tried using " Anaconda3/5.3.0" only, i.e. without "module load ptyhon2.gnu/2.7.3". Generally, Anaconda contains python, and Anaconda3 can manage python2 environments. However, the problem is that Anaconda tries to reach internet for installing modules - that obviously don't work on TSD. We can check with TSD if they have a mirror for Anaconda.

Another option is to try 
```
module load python2.gnu/2.7.15
pip install --user cython
pip install --user --index-url=https://pypi.tsd.usit.no/simple bitarray==0.8 nose==1.3  pybedtools==0.7  scipy==0.18  pandas==0.20 numpy==1.12
```
Could you please try this and let me know if it worked?

**Comment by ofrei** [comment]
Installation-wise it worked for me, but I haven't tried to run ldsc in that environment:
![image](https://user-images.githubusercontent.com/13171449/76508774-3ace1600-644f-11ea-8aab-194cb62a7a62.png)

**Comment by ofrei** [comment]
@E-Claire Good to know this is now working!
```
To activate the conda environment, run: source /cluster/projects/p471/ldsc-activation, substituting p471 for p697 in the command when logged on to p697.

To deactivate run: source deactivate.
```
