### ISSUE TITLE
Make RMarkdown work on linux tsd

### ISSUE THREAD

**Issue by fuyu00** [norment/tsd_issues#45]
Currently RMarkdown documents do not knit to either html or pdf on tsd using RStudio 

To replicate the issue:

Start rstudio (on any node)

Create an rmarkdown document

Press the knit command (selecting either html or pdf)

Error occurs – missing font for html, missing latex package for pdf.

**html output** - X11 font -helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 12 could not be loaded
**pdf output** - 
![image](https://user-images.githubusercontent.com/45471612/97182206-88a84c00-179c-11eb-98e0-8ea00b54961b.png)

**Comment by ofrei** [comment]
@fuyu00 I'm trying to reproduce it.
I've started RStudio on rhel7 thinlink node, then "File" / "New R Makrdown". It asks about installing packages (see screenshot below). I've selected "yes, install" -  but I think some of the packages are trying do download from github, and fails.
![image](https://user-images.githubusercontent.com/13171449/97182767-3d426d80-179d-11eb-9bc5-c49de6545aef.png)
Are you doing it differently?

**Comment by ofrei** [comment]
Among the list above I think only three packages failed to install - ``stringr, knitr, rmarkdown``. Did you managed to get them installed?

**Comment by fuyu00** [comment]
Yes, I have managed to get them installed - also I'm using R version 4.0, though the issue is also present on v 3.6.x

**Comment by fuyu00** [comment]
@ofrei I think the issue you're encountering is due to the "stringi" package which needs a specific install command on tsd as mentioned  [here](https://www.uio.no/english/services/it/research/sensitive-data/use-tsd/software/r/)

**Comment by fuyu00** [comment]
![image](https://user-images.githubusercontent.com/45471612/97190024-8c8c9c00-17a5-11eb-9216-f9da773dd7ee.png)

**Comment by Sandeek** [comment]
The issue is due to the missing ' .TinyTex/'(hidden) folder in the home directory of the user. In the local machine with internet, download tinytex package and install TinyTex using the commands
install.packages('tinytex')
tinytex::install_tinytex()

This installs .TinyTex/ folder in the home directory. Zip this folder and upload to tsd using tsd web portal. Unzip the file in the home directory of the user. 
![image](https://user-images.githubusercontent.com/71389186/99088279-2472ee00-25cc-11eb-809e-17157f9b3e21.png)

(Note: If the tinytex, xfun, rmarkdown packages available in tsd are older, please download in your local machine and upload them as well).
